# Generated by Django 3.0.4 on 2021-04-24 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='members',
            field=models.ManyToManyField(through='simulations.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pump',
            name='_over_pump_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_pump_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='pump',
            name='fluid_level_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluid_level_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='pump',
            name='pump_intake_pressure_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_intake_pressure_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='pump',
            name='total_dynamic_head_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_dynamic_head_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='connection_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_connection_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='duty_cycle_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_duty_cycle_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='efficiency_classes_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_efficiency_classes_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='enclosure_degree_of_protection_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_enclosure_degree_of_protection_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='frame_size_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_size_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='isolation_class_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_isolation_class_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='method_of_cooling_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_method_of_cooling_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='motor_starting_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_motor_starting_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='nominal_frequency_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_nominal_frequency_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='nominal_voltage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_nominal_voltage_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='number_of_phases_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_number_of_phases_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='pole_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_pole_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='rated_output_power_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_rated_output_power_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='winding_type_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winding_type_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='motor',
            name='zone_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motors_by_zone_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Role'),
        ),
        migrations.AddField(
            model_name='membership',
            name='simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulations.Simulation'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='separator',
            name='size_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separator_b_size1', to='simulations.SeparatorSize'),
        ),
        migrations.AddField(
            model_name='separator',
            name='size_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separator_b_size2', to='simulations.SeparatorSize'),
        ),
        migrations.AddField(
            model_name='separator',
            name='size_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separator_b_size3', to='simulations.SeparatorSize'),
        ),
        migrations.AddField(
            model_name='pumpunit',
            name='user_defined_pump_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option'),
        ),
        migrations.AddField(
            model_name='ipr',
            name='ipr_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Option'),
        ),
        migrations.AddField(
            model_name='gearbox',
            name='pulley_belt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='bubble_point_pressure_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_bubble_point_pressure_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='free_gas_at_pump_depth_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_free_gas_at_pump_depth_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='gas_impurities_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_gas_impurities_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='gas_oil_ratio_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_gas_oil_ratio_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='gas_specific_gravity_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_gas_specific_gravity_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='oil_gravity_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_oil_gravity_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='water_cut_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_cut_correlation_option', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='water_specific_gravity_correlation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluids_by_water_specific_gravity_correlation_option', to='main.Option'),
        ),
    ]
