# Generated by Django 3.1.4 on 2021-04-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('simulations', '0002_auto_20210424_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoir',
            name='reservoir_type',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='reservoir_type_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservoirs_by_reservoir_type_option', to='main.option'),
        ),
    ]
