# Generated by Django 3.1.4 on 2021-04-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_auto_20210427_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoir',
            name='id',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='simulation',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='simulations.simulation'),
        ),
    ]
