# Generated by Django 3.1.4 on 2021-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_auto_20210427_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservoir',
            name='acentric_factors',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='flow_rate_vs_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='productivity_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='reservoir_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservoir',
            name='reservoir_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
