# Generated by Django 3.0.4 on 2021-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_auto_20210427_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_user_creator',
            field=models.BooleanField(default=False),
        ),
    ]
