# Generated by Django 3.0.4 on 2021-05-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_membership_is_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_user_creator',
        ),
    ]
