# Generated by Django 3.0.4 on 2021-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0008_membership_is_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='main_token',
            field=models.CharField(default='main_token', max_length=255),
        ),
    ]
