# Generated by Django 3.0.4 on 2021-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0012_auto_20210531_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1, error_messages={'invalid': 'Asadads'}),
        ),
    ]
