# Generated by Django 3.0.4 on 2021-06-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0014_auto_20210531_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='main_token',
        ),
    ]
