# Generated by Django 3.0.4 on 2021-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0015_remove_simulation_main_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
