# Generated by Django 3.0.4 on 2021-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0016_exceltestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltestmodel',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
