# Generated by Django 3.0.4 on 2021-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0017_exceltestmodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasingTubing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('bottom', models.FloatField()),
                ('top', models.FloatField()),
                ('outside_diameter', models.FloatField()),
                ('inside_diameter', models.FloatField()),
                ('roughness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('pump_depth', models.FloatField(blank=True, null=True)),
                ('tubing_pressure', models.FloatField(blank=True, null=True)),
                ('casing_pressure', models.FloatField(blank=True, null=True)),
                ('intake_pressure', models.FloatField(blank=True, null=True)),
                ('fluid_over_pump', models.FloatField(blank=True, null=True)),
                ('tdh', models.FloatField(blank=True, null=True)),
                ('free_gas_intake', models.FloatField(blank=True, null=True)),
                ('pb_depth', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OdWeightId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outside_diameter_OD', models.FloatField()),
                ('inside_diameter_ID', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WellSchematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casing_inside_diameter', models.FloatField(blank=True, null=True)),
                ('casing_outside_Diameter', models.FloatField(blank=True, null=True)),
                ('casing_weight', models.FloatField(blank=True, null=True)),
                ('casing_depth', models.FloatField(blank=True, null=True)),
                ('tubing_inside_diameter', models.FloatField(blank=True, null=True)),
                ('tubing_outside_diameter', models.FloatField(blank=True, null=True)),
                ('tubing_weight', models.FloatField(blank=True, null=True)),
                ('tubing_depth', models.FloatField(blank=True, null=True)),
                ('top_of_perforation', models.FloatField(blank=True, null=True)),
                ('wellbore_correlations', models.FloatField(blank=True, null=True)),
                ('md', models.FloatField(blank=True, null=True)),
                ('tvd', models.FloatField(blank=True, null=True)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('reservoir_temperature', models.FloatField(blank=True, null=True)),
                ('reservoir_pressure', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fluid',
            name='Oil_FVF',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='bubble_point_pressure_correlation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='dead_oil_viscosity_correlation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='gas_viscosity_correlation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='oil_compressibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='oil_formation_volume_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='production_gor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='saturated_oil_viscosity_correlations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='separator_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='separator_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluid',
            name='solution_gas_oil_ratio_correlation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='undersaturated_oil_viscosity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipr',
            name='water_cut',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
