# Generated by Django 3.0.4 on 2021-11-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0018_auto_20211120_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='flow_rate',
            new_name='fluid_rate',
        ),
    ]
