# Generated by Django 3.0.4 on 2021-11-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0019_auto_20211130_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casingtubing',
            name='bottom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingtubing',
            name='inside_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingtubing',
            name='outside_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingtubing',
            name='roughness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingtubing',
            name='top',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingtubing',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
