# Generated by Django 3.0.4 on 2021-12-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('simulations', '0020_auto_20211130_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluid',
            name='bubble_point_pressure_correlation',
        ),
        migrations.RemoveField(
            model_name='fluid',
            name='gas_viscosity',
        ),
        migrations.RemoveField(
            model_name='fluid',
            name='gas_viscosity_correlation',
        ),
        migrations.AddField(
            model_name='fluid',
            name='gas_SP_GR',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='solution_GOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_GOR', to='main.Option'),
        ),
        migrations.AddField(
            model_name='fluid',
            name='tempreture',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluid',
            name='water_SP_GR',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
