# Generated by Django 3.0.4 on 2021-12-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('simulations', '0021_auto_20211203_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluid',
            name='gas_viscosity_correlation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_viscosity_correlation', to='main.Option'),
        ),
    ]
